name: Daily Check Cronjob
on:
  workflow_dispatch:
  schedule:
    # UTC time 3 am is 11 am in Singapore local time
    - cron: "0 3 * * *"

jobs:
  check-updating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install dependencies and build
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks sub-magazines
      - name: Run
        run: cabal run sub-magazines
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
