name: Daily Check Cronjob
on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  check-updating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal run .
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
